// Presentation/DemoReact/src/app/client/ClientDetail.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams } from 'react-router-dom';

// Functions
import { useLoadData } from '../functions';

const ClientDetail = () => {
    const [data = [], setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = parseInt(params.id);

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    useLoadData('/test/client/' + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>View Client</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <button className="btn btn-primary" href="/client/edit/{{ id }}">
                            <FontAwesomeIcon icon="fa-solid fa-pencil" className="me-2" /> Edit
                        </button>
                    </div>
                </div>
                <div className="container data">
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Id
                        </div>
                        <div className="col-10 col-value">
                            {id}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Guid
                        </div>
                        <div className="col-10 col-value">
                            {data.guid}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            TypeId
                        </div>
                        <div className="col-10 col-value">
                            {data.typeId}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Type
                        </div>
                        <div className="col-10 col-value">
                            {data.type}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Name
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.name}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Address (Line 1)
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.addressLine1}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Address (Line 2)
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.addressLine2}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            City
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.city}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Region
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.region}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Postal Code
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.postalCode}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Country
                        </div>
                        <div className="col-10 col-value">
                            <div>{data.country}</div>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Phone Number
                        </div>
                        <div className="col-10 col-value">
                            <a href="tel:{{ data.phoneNumber }}" target="_blank">{data.phoneNumber}</a>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            URL / Website
                        </div>
                        <div className="col-10 col-value">
                            <a href="{{ data.url }}" target="_blank">{data.url}</a>
                        </div>
                    </div>
                </div>
            </div >
        </>
    );
}

export default ClientDetail;

// DemoAngular/src/app/client/client-detail/client-detail.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { IClient } from '../../../models/client.model';
import { ClientService } from '../../../services/client.service';

@Component({
  selector: 'demo-client-detail',
  templateUrl: './client-detail.component.html',
  styleUrls: ['./client-detail.component.css']
})
export class ClientDetailComponent {
  client: any;
  id: number = 0;
  faTrash = faTrash;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private clientSvc: ClientService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });
    this.clientSvc.getClient(this.id).subscribe((client: IClient | undefined) => this.client = client);
  }

  deleteClient() {
    console.log('TODO: Delete Client');
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>View Client</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-primary"  routerLink="/client/edit/{{ client.id }}"><fa-icon [icon]="faPencil"></fa-icon> Edit</button>
    </div>
  </div>
  <div class="container data">
    <div class="row data-row">
      <div class="col-2 col-key">
        Id
      </div>
      <div class="col-10 col-value">
        {{ client.id }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Guid
      </div>
      <div class="col-10 col-value">
        {{ client.guid }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        TypeId
      </div>
      <div class="col-10 col-value">
        {{ client.typeId }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Type
      </div>
      <div class="col-10 col-value">
        {{ client.type }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Name
      </div>
      <div class="col-10 col-value">
        <div>{{ client.name }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Address (Line 1)
      </div>
      <div class="col-10 col-value">
        <div>{{ client.addressLine1 }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Address (Line 2)
      </div>
      <div class="col-10 col-value">
        <div>{{ client.addressLine2 }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        City
      </div>
      <div class="col-10 col-value">
        <div>{{ client.city }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Region
      </div>
      <div class="col-10 col-value">
        <div>{{ client.region }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Postal Code
      </div>
      <div class="col-10 col-value">
        <div>{{ client.postalCode }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Country
      </div>
      <div class="col-10 col-value">
        <div>{{ client.country }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        URL
      </div>
      <div class="col-10 col-value">
        <a href="{{ client.url }}" target="_blank">{{ client.url }}</a>
      </div>
    </div>
  </div>
</div>
