// Presentation/DemoReact/src/app/user/UserEdit.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams, Link } from 'react-router-dom';

// Functions
import { useLoadData } from '../functions';
import { getUserTypes } from '../functions';
import { getRegions } from '../functions';
import { getCountries } from '../functions';

const UserEdit = () => {
    const [data = [], setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = params.id ? parseInt(params.id) : 0;

    const saveChanges = () => {
        alert("TODO: Save changes.");
    }

    const deleteItem = () => {
        alert("TODO: Delete item.");
    }

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    useLoadData('/test/user/' + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>{id == 0 ? "Add" : "Edit"} User</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <Link to={`/user/${id}`} className="btn btn-light border me-2">
                            <FontAwesomeIcon icon="fa-solid fa-x" className="me-2" /> Cancel
                        </Link>
                        <button type="submit" className="btn btn-primary" onClick={() => saveChanges()}>
                            <FontAwesomeIcon icon="fa-solid fa-save" className="me-2" /> Save
                        </button>
                    </div>
                </div>
                <form>
                    <div className="row mb-2">
                        <div className="col">
                            <div className="mb-3">
                                <label htmlFor="firstName" className="form-label">Name</label>
                                <div className="row">
                                    <div className="col">
                                        <input id="firstName" type="text" className="form-control required" aria-label="First Name" value={data.firstName ?? ''} required placeholder="First Name"
                                            onChange={(e) =>
                                                setData({
                                                    ...data,
                                                    firstName: e.target.value,
                                                })
                                            }
                                        />
                                    </div>
                                    <div className="col">
                                        <input id="middleName" type="text" className="form-control required" aria-label="Middle Name" value={data.middleName ?? ''} required placeholder="Middle Name"
                                            onChange={(e) =>
                                                setData({
                                                    ...data,
                                                    middleName: e.target.value,
                                                })
                                            }
                                        />
                                    </div>
                                    <div className="col">
                                        <input id="lastName" type="text" className="form-control required" aria-label="Last Name" value={data.lastName ?? ''} required placeholder="Last Name"
                                            onChange={(e) =>
                                                setData({
                                                    ...data,
                                                    lastName: e.target.value,
                                                })
                                            }
                                        />
                                    </div>
                                </div>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="typeId" className="form-label">User Type</label>
                                <select id="typeId" className="form-select required" aria-label="Type" value={data.typeId ?? 0} required
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            typeId: e.target.value,
                                        })
                                    }
                                >
                                    {getUserTypes().map(item => (
                                        <option key={item.value} value={item.value}>{item.label}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="mb-3">
                                <label htmlFor="phoneNumber" className="form-label">Phone Number</label>
                                <input id="phoneNumber" type="tel" className="form-control" aria-label="Phone Number" value={data.phoneNumber ?? ''}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            phoneNumber: e.target.value,
                                        })
                                    }
                                />
                            </div>
                            <div className="mb-3">
                                <label htmlFor="url" className="form-label">URL / Website</label>
                                <input id="url" type="url" className="form-control" aria-label="URL" value={data.url ?? ''}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            url: e.target.value,
                                        })
                                    }
                                />
                            </div>
                            <div className="mb-3">
                                <input id="isActive" type="checkbox" className="form-check-input me-2" aria-label="Active" checked={data.isActive ?? false}
                                    onChange={(e) =>
                                        setData({
                                            ...data,
                                            isActive: e.target.checked,
                                        })
                                    }
                                />
                                <label htmlFor="isActive" className="form-label">Active</label>
                            </div>
                        </div>
                        <div className="col">
                            <div className="card">
                                <div className="card-header">Address</div>
                                <div className="card-body">
                                    <div className="mb-3">
                                        <div className="mb-3">
                                            <label htmlFor="addressLine1" className="form-label">Address</label>
                                            <input id="addressLine1" type="text" className="form-control mb-2" aria-label="Address Line 1" value={data.addressLine1 ?? ''} placeholder="Line 1..."
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        addressLine1: e.target.value,
                                                    })
                                                }
                                            />
                                            <input id="addressLine2" type="text" className="form-control mb-3" aria-label="Address Line 2" value={data.addressLine2 ?? ''} placeholder="Line 2..."
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        addressLine2: e.target.value,
                                                    })
                                                }
                                            />
                                            <div className="mb-3">
                                                <label htmlFor="city" className="form-label">City</label>
                                                <input id="city" type="text" className="form-control mt-2" aria-label="city" value={data.city ?? ''} placeholder="City..."
                                                    onChange={(e) =>
                                                        setData({
                                                            ...data,
                                                            city: e.target.value,
                                                        })
                                                    }
                                                />
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col">
                                                <div className="mb-3">
                                                    <label htmlFor="region" className="form-label">Region</label>
                                                    <input id="region" type="text" list="regionList" className="form-control mb-2" aria-label="Region" value={data.region ?? ''} placeholder="Type to search..."
                                                        onChange={(e) =>
                                                            setData({
                                                                ...data,
                                                                region: e.target.value,
                                                            })
                                                        }
                                                    />
                                                    <datalist id="regionList">
                                                        {getRegions().map(item => (
                                                            <option key={item.value} value={item.value}>{item.label}</option>
                                                        ))}
                                                    </datalist>
                                                </div>
                                            </div>
                                            <div className="col">
                                                <div className="mb-3">
                                                    <label htmlFor="postalCode" className="form-label">Postal Code</label>
                                                    <input id="postalCode" type="text" className="form-control mb-2" aria-label="Postal Code" value={data.postalCode ?? ''}
                                                        onChange={(e) =>
                                                            setData({
                                                                ...data,
                                                                postalCode: e.target.value,
                                                            })
                                                        }
                                                    />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="mb-3">
                                            <label htmlFor="country" className="form-label">Country</label>
                                            <select id="country" className="form-select" aria-label="Country" value={data.country ?? ''}
                                                onChange={(e) =>
                                                    setData({
                                                        ...data,
                                                        country: e.target.value,
                                                    })
                                                }
                                            >
                                                {getCountries().map(item => (
                                                    <option key={item.value} value={item.value}>{item.label}</option>
                                                ))}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form >
                <div className="row" className={id == 0 ? 'hidden' : ''}>
                    <div className="col text-end">
                        <button type="submit" className="btn btn-danger" onClick={() => deleteItem()}>
                            <FontAwesomeIcon icon="fa-solid fa-trash" className="me-2" /> Delete
                        </button>
                    </div>
                </div>
            </div >
        </>
    );
}

export default UserEdit;

// Presentation/DemoAngular/src/app/user/user-edit/user-edit.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { faX } from '@fortawesome/free-solid-svg-icons';
import { faSave } from '@fortawesome/free-solid-svg-icons';
import { IUser } from '../../../models/user.model';
import { UserService } from '../../../services/user.service';

declare var bootbox: any;

@Component({
  selector: 'demo-user-edit',
  templateUrl: './user-edit.component.html',
  styleUrls: ['./user-edit.component.css']
})
export class UserEditComponent {
  id: number = 0;
  user: any;
  faTrash = faTrash;
  faX = faX;
  faSave = faSave;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private userSvc: UserService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });

    if (this.id === 0) {
      // Create new User
      this.user = {
        id: 0,
        guid: '',
        typeId: 0,
        type: '',
        isActive: true,
        isDeleted: false,
        firstName: '',
        middleName: '',
        lastName: '',
        addressLine1: '',
        addressLine2: '',
        city: '',
        region: '',
        postalCode: '',
        country: '',
        phoneNumber: '',
      }
    }
    else {
      // Get User
      this.userSvc.getUser(this.id).subscribe((user: IUser | undefined) => this.user = user);
    }
  }

  saveUser() {
    bootbox.alert('TODO: Save User');
  }

  deleteUser() {
    bootbox.confirm('Are you sure you want to delete this User?', (result: boolean) => {
      if (result) {
        bootbox.alert('TODO: Delete User');
      }
    });
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>{{ id === 0 ? 'Add' : 'Edit' }} User</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-light border me-2" routerLink="/users"><fa-icon [icon]="faX"></fa-icon> Cancel</button>
      <button type="submit" class="btn btn-primary" (click)="saveUser()"><fa-icon [icon]="faSave"></fa-icon> Save</button>
    </div>
  </div>
  <form>
    <div class="row mb-2">
      <div class="col">
        <div class="mb-3">
          <label for="name" class="form-label">Name</label>
          <div class="row">
            <div class="col">
              <input class="form-control required" required id="firstName" value="{{ user.firstName }}" placeholder="First...">
            </div>
            <div class="col">
              <input class="form-control" id="middleName" value="{{ user.middleName }}" placeholder="Middle...">
            </div>
            <div class="col">
              <input class="form-control required" required id="lastName" value="{{ user.lastName }}" placeholder="Last...">
            </div>
          </div>
        </div>
        <div class="mb-3">
          <label for="typeId" class="form-label">User Type</label>
          <select class="form-select required" required aria-label="Type" id="typeId" name="typeId" [(ngModel)]="user.typeId">
            <option selected>Select...</option>
            <option value="1">Admin</option>
            <option value="2">Client</option>
            <option value="3">Sales</option>
            <option value="4">Marketing</option>
            <option value="5">Accounting</option>
            <option value="6">Executive</option>
            <option value="7">Developer</option>
          </select>
        </div>
        <div class="mb-3">
          <label for="phoneNumber" class="form-label">Phone Number</label>
          <input type="tel" class="form-control" id="phoneNumber" value="{{ user.phoneNumber }}">
        </div>
        <div class="mb-3">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="isActive" checked="{{ user.isActive }}">
            <label class="form-check-label" for="isActive">
              Active
            </label>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card">
          <div class="card-header">
            Address
          </div>
          <div class="card-body">
            <div class="mb-3">
              <label for="address1" class="form-label">Address</label>
              <input class="form-control mb-3" id="addressLine1" placeholder="Line 1..." value="{{ user.addressLine1 }}">
              <input class="form-control" id="addressLine2" placeholder="Line 2..." value="{{ user.addressLine2 }}">
            </div>
            <div class="mb-3">
              <label for="city" class="form-label">City</label>
              <input class="form-control" id="city" value="{{ user.city }}">
            </div>
            <div class="row">
              <div class="col">
                <div class="mb-3">
                  <label for="region" class="form-label">Region</label>
                  <input class="form-control" list="datalistOptions" id="region" name="region" placeholder="Type to search..." [(ngModel)]="user.region">
                  <datalist id="datalistOptions">
                    <option value="AL">Alabama</option>
                    <option value="AB">Alberta</option>
                    <option value="BC">British Columbia</option>
                    <option value="MB">Manitoba</option>
                    <option value="NB">New Brunswick</option>
                    <option value="NL">Newfoundland and Labrador</option>
                    <option value="NS">Nova Scotia</option>
                    <option value="NT">Northwest Territories</option>
                    <option value="NU">Nunavut</option>
                    <option value="ON">Ontario</option>
                    <option value="PE">Prince Edward Island</option>
                    <option value="QC">Quebec</option>
                    <option value="SK">Saskatchewan</option>
                    <option value="YT">Yukon</option>
                    <hr />
                    <option value="ENG">England</option>
                    <option value="NIR">Northern Ireland</option>
                    <option value="SCT">Scotland</option>
                    <option value="WLS">Wales</option>
                    <option value="IOM">Isle of Man</option>
                    <option value="GIB">Gibraltar</option>
                    <option value="GGY">Guernsey</option>
                    <option value="JEY">Jersey</option>
                    <hr />
                    <option value="AK">Alaska</option>
                    <option value="AZ">Arizona</option>
                    <option value="AR">Arkansas</option>
                    <option value="CA">California</option>
                    <option value="CO">Colorado</option>
                    <option value="CT">Connecticut</option>
                    <option value="DE">Delaware</option>
                    <option value="FL">Florida</option>
                    <option value="GA">Georgia</option>
                    <option value="HI">Hawaii</option>
                    <option value="ID">Idaho</option>
                    <option value="IL">Illinois</option>
                    <option value="IN">Indiana</option>
                    <option value="IA">Iowa</option>
                    <option value="KS">Kansas</option>
                    <option value="KY">Kentucky</option>
                    <option value="LA">Louisiana</option>
                    <option value="ME">Maine</option>
                    <option value="MD">Maryland</option>
                    <option value="MA">Massachusetts</option>
                    <option value="MI">Michigan</option>
                    <option value="MN">Minnesota</option>
                    <option value="MS">Mississippi</option>
                    <option value="MO">Missouri</option>
                    <option value="MT">Montana</option>
                    <option value="NE">Nebraska</option>
                    <option value="NV">Nevada</option>
                    <option value="NH">New Hampshire</option>
                    <option value="NJ">New Jersey</option>
                    <option value="NM">New Mexico</option>
                    <option value="NY">New York</option>
                    <option value="NC">North Carolina</option>
                    <option value="ND">North Dakota</option>
                    <option value="OH">Ohio</option>
                    <option value="OK">Oklahoma</option>
                    <option value="OR">Oregon</option>
                    <option value="PA">Pennsylvania</option>
                    <option value="RI">Rhode Island</option>
                    <option value="SC">South Carolina</option>
                    <option value="SD">South Dakota</option>
                    <option value="TN">Tennessee</option>
                    <option value="TX">Texas</option>
                    <option value="UT">Utah</option>
                    <option value="VT">Vermont</option>
                    <option value="VA">Virginia</option>
                    <option value="WA">Washington</option>
                    <option value="WV">West Virginia</option>
                    <option value="WI">Wisconsin</option>
                    <option value="WY">Wyoming</option>
                  </datalist>
                </div>

              </div>
              <div class="col">
                <div class="mb-3">
                  <label for="postalCode" class="form-label">Postal Code</label>
                  <input class="form-control" id="postalCode" value="{{ user.postalCode }}">
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="country" class="form-label">Country</label>
              <select class="form-select" aria-label="Country" id="country" name="country" [(ngModel)]="user.country">
                <option selected>Select...</option>
                <option value="Canada">Canada</option>
                <option value="United Kingdom">United Kingdom</option>
                <option value="United States">United States</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
  <div *ngIf="id != 0" class="row">
    <div class="col text-end">
      <button class="btn btn-danger" (click)="deleteUser()"><fa-icon [icon]="faTrash"></fa-icon> Delete</button>
    </div>
  </div>
</div>
