// Presentation/DemoReact/src/app/user/UserDetail.jsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import { useParams } from 'react-router-dom';

// Functions
import { useLoadData } from '../functions';

const UserDetail = () => {
    const [data = [], setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState();
    const params = useParams();
    const id = parseInt(params.id);

    // ------------------------------------------------------------
    // Load data
    // ------------------------------------------------------------

    useLoadData('/test/user/' + id, setIsLoading, setData, setError);

    // ------------------------------------------------------------
    // Presentation Layer
    // ------------------------------------------------------------

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h1>User Detail</h1>
                    </div>
                    <div className="col text-end mt-2">
                        <button className="btn btn-primary" href="/user/edit/{{id }}">
                            <FontAwesomeIcon icon="fa-solid fa-pencil" className="me-2" /> Edit
                        </button>
                    </div>
                </div>
                <div className="container data">
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Id
                        </div>
                        <div className="col-10 col-value">
                            {id}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Guid
                        </div>
                        <div className="col-10 col-value">
                            {data.guid}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            TypeId
                        </div>
                        <div className="col-10 col-value">
                            {data.typeId}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Type
                        </div>
                        <div className="col-10 col-value">
                            {data.type}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Email Address
                        </div>
                        <div className="col-10 col-value">
                            <a href="mailto:{{ data.emailAddress }}">{data.emailAddress}</a>
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            First Name
                        </div>
                        <div className="col-10 col-value">
                            {data.firstName}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Middle Name
                        </div>
                        <div className="col-10 col-value">
                            {data.middleName}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Last Name
                        </div>
                        <div className="col-10 col-value">
                            {data.lastName}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Address (Line 1)
                        </div>
                        <div className="col-10 col-value">
                            {data.addressLine1}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Address (Line 2)
                        </div>
                        <div className="col-10 col-value">
                            {data.addressLine2}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            City
                        </div>
                        <div className="col-10 col-value">
                            {data.city}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Region
                        </div>
                        <div className="col-10 col-value">
                            {data.region}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Postal Code
                        </div>
                        <div className="col-10 col-value">
                            {data.postalCode}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Country
                        </div>
                        <div className="col-10 col-value">
                            {data.country}
                        </div>
                    </div>
                    <div className="row data-row">
                        <div className="col-2 col-key">
                            Phone Number
                        </div>
                        <div className="col-10 col-value">
                            <a href="tel:{{ data.phoneNumber }}" target="_blank">{data.phoneNumber}</a>
                        </div>
                    </div>
                </div>
            </div >

        </>
    );
}

export default UserDetail;

// DemoAngular/src/app/user/user-detail/user-detail.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { IUser } from '../../../models/user.model';
import { UserService } from '../../../services/user.service';

@Component({
  selector: 'demo-user-detail',
  templateUrl: './user-detail.component.html',
  styleUrls: ['./user-detail.component.css']
})
export class UserDetailComponent {
  user: any;
  id: number = 0;
  faTrash = faTrash;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private userSvc: UserService
  ) { }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      this.id = parseInt(params.get('id') ?? '0') ?? 0;
    });
    this.userSvc.getUser(this.id).subscribe((user: IUser | undefined) => this.user = user);
  }

  deleteUser() {
    console.log('TODO: Delete User');
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>User Detail</h1>
    </div>
    <div class="col text-end mt-2">
      <button class="btn btn-primary" routerLink="/user/edit/{{ user.id }}"><fa-icon [icon]="faPencil"></fa-icon> Edit</button>
    </div>
  </div>
  <div class="container data">
    <div class="row data-row">
      <div class="col-2 col-key">
        Id
      </div>
      <div class="col-10 col-value">
        {{ user.id }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Guid
      </div>
      <div class="col-10 col-value">
        {{ user.guid }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        TypeId
      </div>
      <div class="col-10 col-value">
        {{ user.typeId }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Type
      </div>
      <div class="col-10 col-value">
        {{ user.type }}
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Email Address
      </div>
      <div class="col-10 col-value">
        <div><a href="mailto:{{ user.emailAddress }}">{{ user.emailAddress }}</a></div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        First Name
      </div>
      <div class="col-10 col-value">
        <div>{{ user.firstName }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        First Name
      </div>
      <div class="col-10 col-value">
        <div>{{ user.middleName }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        First Name
      </div>
      <div class="col-10 col-value">
        <div>{{ user.lastName }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Address
      </div>
      <div class="col-10 col-value">
        <div>{{ user.address }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        City
      </div>
      <div class="col-10 col-value">
        <div>{{ user.city }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Region
      </div>
      <div class="col-10 col-value">
        <div>{{ user.region }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Postal Code
      </div>
      <div class="col-10 col-value">
        <div>{{ user.postalCode }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Country
      </div>
      <div class="col-10 col-value">
        <div>{{ user.country }}</div>
      </div>
    </div>
    <div class="row data-row">
      <div class="col-2 col-key">
        Phone Number
      </div>
      <div class="col-10 col-value">
        <a href="tel:{{ user.phoneNumber }}" target="_blank">{{ user.phoneNumber }}</a>
      </div>
    </div>
  </div>
</div>
